"""
add_phone_number_to_user

Revision ID: 04a9bc2ccf25
Revises:
Create Date: 2025-11-24 15:11:06.165036

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "04a9bc2ccf25"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
