"""
add_move_elememts_to_user

Revision ID: 567f789ab029
Revises: 5e73928fe9f1
Create Date: 2025-11-24 20:42:34.747045

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "567f789ab029"
down_revision: str | Sequence[str] | None = "5e73928fe9f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faculty",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "interest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculty.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("second_name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculty.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "user_interest",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("interest_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.drop_table("interests")
    op.drop_table("groups")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("faculties")
    op.drop_table("user_interest_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_interest_association",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("interest_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "interest_id"),
    )
    op.create_table(
        "faculties",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("telegram_id", sa.INTEGER(), nullable=True),
        sa.Column("first_name", sa.VARCHAR(), nullable=True),
        sa.Column("second_name", sa.VARCHAR(), nullable=True),
        sa.Column("surname", sa.VARCHAR(), nullable=True),
        sa.Column("phone_number", sa.VARCHAR(), nullable=True),
        sa.Column("faculty_id", sa.INTEGER(), nullable=True),
        sa.Column("group_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=1)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("faculty_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interests",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.drop_table("user_interest")
    op.drop_table("user")
    op.drop_table("group")
    op.drop_table("interest")
    op.drop_table("faculty")
    # ### end Alembic commands ###
