"""
initial_schema

Revision ID: 5e73928fe9f1
Revises: 04a9bc2ccf25
Create Date: 2025-11-24 15:11:59.399332

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5e73928fe9f1"
down_revision: str | Sequence[str] | None = "04a9bc2ccf25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
